services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: milkfarm
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/milkfarm
      ADMIN_IDS: ${ADMIN_IDS}

volumes:
  pgdata:
